environment: production

server:
  port: 80
  ssl:
    enabled: false

spring:
    profiles: prod
    couchbase:
        bootstrap-hosts: 127.0.0.1
        bucket:
          name: testbucket
          password: testbucket

security:
  oauth2:
    client:
      access-token-validity-seconds: 5000
      refresh-token-validity-seconds: 50000
      

logging:
  config: classpath:log4j2-prod.xml
